<link
        rel="apple-touch-icon"
        sizes="180x180"
        href="/img/icons/apple-touch-icon.png"
>
<link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/img/icons/favicon-32x32.png"
>
<link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/img/icons/favicon-16x16.png"
>
<link
        rel="mask-icon"
        href="/img/icons/safari-pinned-tab.svg"
        color="#ec2f4b"
>
<link
        rel="shortcut icon"
        href="/img/icons/favicon.ico"
>
<meta
        name="apple-mobile-web-app-title"
        content="PhpUnitGen"
>
<meta
        name="application-name"
        content="PhpUnitGen"
>
<meta
        name="msapplication-TileColor"
        content="#2b5797"
>
<meta
        name="msapplication-config"
        content="/img/icons/browserconfig.xml"
>
<meta
        name="theme-color"
        content="#ffffff"
>
