language: php

dist: trusty

git:
  depth: false

addons:
  sonarcloud:
    organization: "paul-thebaud-github"
    token: ${SONAR_TOKEN}

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4

before_install:
  - nvm install 13.2

before_script:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - composer self-update
  - composer global require hirak/prestissimo
  - composer install --no-interaction --no-suggest --no-progress
  - yarn install --non-interactive

install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config

script:
  - yarn lint
  - yarn build
  - phpdbg -qrr ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner

deploy:
  - provider: script
    script: bash docker_push_staging
    on:
      branch: develop
  - provider: script
    script: bash docker_push_prod
    on:
      branch: master
