version: '2'
services:
  phpunitgen-phpfpm:
    build:
      context: .
      dockerfile: docker/Dockerfile-phpfpmalpine
    container_name: phpunitgen-phpfpm
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - app-network
  phpunitgen-nginx:
    build:
      context: .
      dockerfile: docker/local/Dockerfile-nginxalpine
    container_name: phpunitgen-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/local/local.pem:/local.pem
      - ./nginx/local/local-key.pem:/local-key.pem
    networks:
      - app-network
networks:
  app-network:
    driver: bridge