#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t paulthebaud/phpunitgen-phpfpm -f ./docker/Dockerfile-phpfpmalpine .
docker build -t paulthebaud/phpunitgen-nginx -f ./docker/production/Dockerfile-phpfpmalpine .
docker push paulthebaud/phpunitgen-nginx:staging
docker push paulthebaud/phpunitgen-phpfpm:staging
