version: '2'
services:
  phpunitgen-phpfpm:
    build:
      context: .
      dockerfile: docker/local/Dockerfile-phpfpmalpine
    container_name: phpunitgen-phpfpm
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
    networks:
      - app-network
  phpunitgen-nginx:
    image: nginx:alpine
    container_name: phpunitgen-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/local/app.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/local/local.pem:/local.pem
      - ./nginx/local/local-key.pem:/local-key.pem
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge