#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t paulthebaud/phpunitgen-phpfpm -f ./docker/production/Dockerfile-phpfpmalpine .
docker build -t paulthebaud/phpunitgen-nginx -f ./docker/production/Dockerfile-nginxalpine .
docker push paulthebaud/phpunitgen-nginx
docker push paulthebaud/phpunitgen-phpfpm
kubectl create namespace phpunitgen
kubectl apply -k kubernetes/production/
kubectl rollout restart deployment/phpunitgen-nginx -n phpunitgen
kubectl rollout restart deployment/phpunitgen-phpfpm -n phpunitgen