import Vue from "vue";
import { AlertPlugin } from "bootstrap-vue/src/components/alert";
import { BadgePlugin } from "bootstrap-vue/src/components/badge";
import { ButtonPlugin } from "bootstrap-vue/src/components/button";
import { CardPlugin } from "bootstrap-vue/src/components/card";
import { CollapsePlugin } from "bootstrap-vue/src/components/collapse";
import { DropdownPlugin } from "bootstrap-vue/src/components/dropdown";
import { FormPlugin } from "bootstrap-vue/src/components/form";
import { FormCheckboxPlugin } from "bootstrap-vue/src/components/form-checkbox";
import { FormInputPlugin } from "bootstrap-vue/src/components/form-input";
import { InputGroupPlugin } from "bootstrap-vue/src/components/input-group";
import { LayoutPlugin } from "bootstrap-vue/src/components/layout";
import { NavPlugin } from "bootstrap-vue/src/components/nav";
import { NavbarPlugin } from "bootstrap-vue/src/components/navbar";
import { ToastPlugin } from "bootstrap-vue/src/components/toast";
import { TooltipPlugin } from "bootstrap-vue/src/components/tooltip";

Vue.use(AlertPlugin);
Vue.use(BadgePlugin);
Vue.use(ButtonPlugin);
Vue.use(CardPlugin);
Vue.use(CollapsePlugin);
Vue.use(DropdownPlugin);
Vue.use(FormPlugin);
Vue.use(FormCheckboxPlugin);
Vue.use(FormInputPlugin);
Vue.use(InputGroupPlugin);
Vue.use(LayoutPlugin);
Vue.use(NavPlugin);
Vue.use(NavbarPlugin);
Vue.use(ToastPlugin);
Vue.use(TooltipPlugin);
