apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: phpunitgen-cert
spec:
  secretName: phpunitgen-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: phpunitgen.io
  dnsNames:
    - phpunitgen.io
