apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: phpunitgen-cert
spec:
  secretName: phpunitgen-cert
  issuerRef:
    name: letsencrypt-prod
  commonName: phpunitgen.io
  dnsNames:
    - phpunitgen.io