apiVersion: v1
kind: Service
metadata:
  name: phpunitgen-phpfpm-staging
spec:
  ports:
  - name: fpm
    port: 9000
    targetPort: 9000
  selector:
    phpunitgen: phpunitgen-phpfpm-staging
status:
  loadBalancer: {}
