FROM node:alpine AS builder
COPY . /app
WORKDIR /app/
RUN yarn install
RUN yarn build

FROM nginx:alpine

COPY --from=builder /app/public /var/www/public

COPY nginx/app.conf /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
EXPOSE 443