FROM node:18-alpine AS builder
ARG MIX_GOOGLE_ANALYTICS_ID
ENV MIX_GOOGLE_ANALYTICS_ID=$MIX_GOOGLE_ANALYTICS_ID
COPY . /app
WORKDIR /app/
RUN yarn install
RUN yarn build

FROM nginx:alpine

COPY --from=builder /app/public /var/www/public

COPY nginx/production/app.conf /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
