apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: phpunitgen-cert-staging
spec:
  secretName: phpunitgen-cert-staging
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: staging.phpunitgen.io
  dnsNames:
    - staging.phpunitgen.io
