name: CICD

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.11.0
        with:
          php-version: 7.4
          coverage: xdebug

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.2

      - name: Install dependencies
        run: |
          composer self-update
          composer install --no-interaction --no-progress
          yarn install --non-interactive

      - name: Execute lint
        run: yarn lint

      - name: Build JS
        run: yarn build

      - name: Execute tests
        run: vendor/bin/phpunit -c phpunit.xml.dist

      - name: Prepare SonarCloud Scan
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' .coverage/clover.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Production - Build and push PHP FPM
        id: docker_build_php
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          file: ./docker/production/Dockerfile-phpfpmalpine
          build-args: MIX_GOOGLE_ANALYTICS_ID="$MIX_GOOGLE_ANALYTICS_ID"
          push: true
          tags: paulthebaud/phpunitgen-phpfpm:latest
        env:
          MIX_GOOGLE_ANALYTICS_ID: ${{ secrets.MIX_GOOGLE_ANALYTICS_ID }}

      - name: Production - Build and push Nginx
        id: docker_build_nginx
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          file: ./docker/production/Dockerfile-nginxalpine
          build-args: MIX_GOOGLE_ANALYTICS_ID="$MIX_GOOGLE_ANALYTICS_ID"
          push: true
          tags: paulthebaud/phpunitgen-nginx:latest
        env:
          MIX_GOOGLE_ANALYTICS_ID: ${{ secrets.MIX_GOOGLE_ANALYTICS_ID }}

      - name: Staging - Build and push PHP FPM
        id: docker_build_php_staging
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/develop'
        with:
          file: ./docker/staging/Dockerfile-phpfpmalpine
          build-args: MIX_GOOGLE_ANALYTICS_ID="$MIX_GOOGLE_ANALYTICS_ID"
          push: true
          tags: paulthebaud/phpunitgen-phpfpm:staging
        env:
          MIX_GOOGLE_ANALYTICS_ID: ${{ secrets.MIX_GOOGLE_ANALYTICS_ID }}

      - name: Staging - Build and push Nginx
        id: docker_build_nginx_staging
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/develop'
        with:
          file: ./docker/staging/Dockerfile-nginxalpine
          build-args: MIX_GOOGLE_ANALYTICS_ID="$MIX_GOOGLE_ANALYTICS_ID"
          push: true
          tags: paulthebaud/phpunitgen-nginx:staging
        env:
          MIX_GOOGLE_ANALYTICS_ID: ${{ secrets.MIX_GOOGLE_ANALYTICS_ID }}

      - name: Production - Update deployment
        uses: steebchen/kubectl@v2.0.0
        if: github.ref == 'refs/heads/master'
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          command: apply -k kubernetes/production/

      - name: Staging - Update deployment
        uses: steebchen/kubectl@v2.0.0
        if: github.ref == 'refs/heads/develop'
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          command: apply -k kubernetes/staging/

      - name: Production - Restart deployment PHP FPM
        uses: steebchen/kubectl@v2.0.0
        if: github.ref == 'refs/heads/master'
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          command: rollout restart deployment/phpunitgen-phpfpm --namespace=phpunitgen

      - name: Staging - Restart deployment PHP FPM
        uses: steebchen/kubectl@v2.0.0
        if: github.ref == 'refs/heads/develop'
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          command: rollout restart deployment/phpunitgen-phpfpm-staging --namespace=phpunitgen-staging

      - name: Production - Restart deployment Nginx
        uses: steebchen/kubectl@v2.0.0
        if: github.ref == 'refs/heads/master'
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          command: rollout restart deployment/phpunitgen-nginx --namespace=phpunitgen

      - name: Staging - Restart deployment Nginx
        uses: steebchen/kubectl@v2.0.0
        if: github.ref == 'refs/heads/develop'
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          command: rollout restart deployment/phpunitgen-nginx-staging --namespace=phpunitgen-staging
